### PR TITLE
Major contribution (2/3 and 3/3)

### PR DESCRIPTION
**Pull request by allsey87**
This pull request is the second of three large requests that push the features used by the swarm construction project upstream and into the most recent version of ARGoS. This commit adds a dynamics3d physics engine plugin based on the Bullet Physics SDK.

I have also added initialization to a previously uninitialized variable in the dynamics2d multi-body model that was causing a compilation warning.

The code quality inside the Bullet Physics SDK is average at the best of times and generates a lot of warnings. I have turned these warnings off using CMake (see [line 421 of plugins/simulator/ physics_engines/dynamics3d/CMakeLists.txt](https://github.com/allsey87/argos3/blob/master/src/plugins/simulator/physics_engines/dynamics3d/CMakeLists.txt#L421)) so they do not distract from warnings related to ARGoS / user code.

### CODE REVIEW

**Comment by allsey87** [comment]
Note, of the 111,904 lines of code being committed, 108,802 lines of code belong to the bullet library.

**Comment by allsey87** [comment]
UPDATE: I have added the final commits from my work to this pull request. These commits:
1. Fix a small issue in the dynamics3d_model.h class,
2. Add in some missing classes for the directional LED entity (I tried to reuse the existing classes but it was causing issues when both LED types were being used at the same time),
3. Update the enable/disable logic for the directional led, tag, and radio entities
4. Introduce the prototyping plugin
5. Add examples for all this work under `src/testing/examples` (I recommend checking these out! :))

**Comment by allsey87** [comment]
All code compiles and the examples have been tested under Ubuntu 17.04 and Ubuntu 16.04.

**Comment by ilpincy** [comment]
I have added a few small changes that fix segfaults due to attributes not initialized in the prototype entity and in the radio entity. There still is a memory corruption upon exit in footbot_camera_prototype_example.argos.

**Comment by ilpincy** [comment]
It's a segfault when the experiment is destroyed. I sent you the relevant log by email to your private account.

**Comment by allsey87** [comment]
I'll look into it tomorrow. I suspect this has something to do with the unmovable boundary boxes which are added to both physics engines.

**Comment by allsey87** [comment]
I have addressed the raised issues. I believe the code is now ready to be merged and to be released as part of 3.0.0-beta50.

**Pull request merged**
