### PR TITLE
Major contribution (1/3)

### PR DESCRIPTION
**Pull request by allsey87**
Sorry about closing and reopening, I didn't realise that newer commits to branch would automatically be appended to the pull request. As stated in one of the commit messages, this is the first of three large commits that push the features used by the swarm construction project upstream and into the most recent version of ARGoS. This commit adds several new entities into ARGoS and their respective sensor and actuator interfaces/implementations where applicable. The new plugins are fully documented and have Lua wrappers where applicable.

In addition, there are two commits in this pull request that (i) fix a linking bug in the ARGoS testing folder, and (ii) tell cmake to set the target compiler to ISO C++14 mode.

### CODE REVIEW

**Comment by allsey87** [comment]
Sorry about closing and reopening, I didn't realise that newer commits to branch would automatically be appended to the pull request. As stated in one of the commit messages, this is the first of three large commits that push the features used by the swarm construction project upstream and into the most recent version of ARGoS. This commit adds several new entities into ARGoS and their respective sensor and actuator interfaces/implementations where applicable. The new plugins are fully documented and are have Lua wrappers where applicable.

In addition, there are two commits in this pull request that (i) fix a linking bug in the ARGoS testing folder, and (ii) tell cmake to set the target compiler to ISO C++14 mode.

**Comment by allsey87** [comment]
Checking out a fresh copy, compiling in release mode, and running ARGoS on `/src/testing/examples/footbot_camera_example.argos` confirms that these changes work on Ubuntu 17.04 with GCC 6.3.0 and on Ubuntu 16.04.4 LTS with GCC 5.4.0.

**Comment by ilpincy** [comment]
Thanks, I'll look at the code. Why are we switching to C++14? Not all code included in ARGoS complies with that, and Qt-CMake compilation might not go as intended. I'd stick to C++11.

**Comment by allsey87** [comment]
Thanks for having a look at this. The motivation for setting C++14 as the standard is as follows:
1. You are already conditionally doing this ([see line 77 of  ARGoSCheckQTOpenGL.cmake](https://github.com/ilpincy/argos3/blob/master/src/cmake/ARGoSCheckQTOpenGL.cmake#L77))
2. C++14 is switched on by default in GCC versions higher than 6.1.0, so if this isn't specified in the CMake, this is what you are getting
3. The next LTS release of Ubuntu should be next month, which will likely ship with a GCC version newer than 6.1.0 (17.04 shipped with 6.3.0)
4. As far as I can tell, all of the ARGoS code base (including the Qt-CMake code) compiles and works under both C++11 and C++14 (I have tested this on Ubuntu 17.04 with GCC 6.3.0 and on Ubuntu 16.04.4 LTS with GCC 5.4.0). The only things I haven't tested are the physx engine and compilation under an OS X toolchain / on a OS X system.
5. With very few exceptions ([for example, storage class specifiers](http://en.cppreference.com/w/cpp/language/storage_duration)), C++11 and C++14 are only adding features to the language and making it more flexible and easier to use. They generally don't break anything and one is not forced to use the new features if they don't want to.

**Comment by ilpincy** [comment]
I had a look at the code and it looks excellent. OK also for the global switch to C++14. Thanks a lot for all the work! :-)

**Pull request merged**
