### PR TITLE
Minor fixes and changes

### PR DESCRIPTION
**Pull request by pawel-jakubowski**
Hi,

During my work with ARGoS I have made some minor fixes and changes that makes my work easier. I hope you will also find it useful.

Only one fix is important - bug with drawing polygons. Without this fix drawing multiple polygons cause additive translation.

Example:
I draw 3 squares with translation (1,1,1).
```
for (int i = 0; i < 3; i++)
    DrawPolygon(
        CVector3(1,1,1),
        CQuaternion(CRadians::ZERO, CVector3(1,0,0)),
        points,
        CColor::BLACK,
        false);
```
1st square has translation (1,1,1)
2nd square has translation (2,2,2) (should be 1,1,1)
3rd square has translation (3,3,3) (should be 1,1,1)

### CODE REVIEW

**Comment by allsey87** [comment]
Regarding compiling ARGoS with C++11, are you using an updated version of CMake as well? CMake 3.0+ supports: `set_property(TARGET target PROPERTY CXX_STANDARD 11)`, perhaps this should be optionally set in ARGoSBuildFlags.cmake to ensure the whole project is being built using one standard or the other. Otherwise compatibility issues arise since std::string, std::istream, etc in c++11 is not the same as the versions in c++03...

**Comment by pawel-jakubowski** [comment]
@allsey87 I did not set c++11 flag in ARGoS cmakes - it is not my decision to make. It can be set by user with CXXFLAGS env variable.
Besides, auto_ptr bothers me the most (all those warnings in gcc 5.2, blah)

**Comment by ilpincy** [comment]
Hi Pawel, thanks for your work! I finally got around to looking at your changes, and they're all great. Thanks again! :-)

**Comment by pawel-jakubowski** [comment]
That's great that I could contribute to this great piece of software :)

**Pull request merged**
