### PR TITLE
Allow argos3 to be embedd in other projects

### PR DESCRIPTION
**Pull request by pawel-jakubowski**
Hi,

I have made some minor changes to cmake files, because used variables makes difficult embedding argos as subdirectory of bigger project.

I also provide:
- Fix for string_utilities.h (this produce compilation error for me on g++ 5.2).
- Change to take ARGOS_PLUGIN_PATH variable paths above predefined paths. This allows to always take currently build libraries and skip those installed in system.

Please review if it is useful for you.

PS. You can check how I used it in [my repository](https://github.com/pawel-jakubowski/coverage-search)

### CODE REVIEW

**Comment by ilpincy** [comment]
Hi Pawel,

Thanks for this contribution, I'll go through it. Thanks in particular for
the compilation fixes!

Just a question. I don't understand why you embedded the entire ARGoS
source into your project. Could you please explain to me why you followed
this path, rather than doing what is shown in the ARGoS embedding examples?

Cheers,
Carlo

On Wed, Apr 6, 2016 at 2:12 PM, Paweł Jakubowski <notifications@github.com>
wrote:

> Hi,
>
> I have made some minor changes to cmake files, because used variables
> makes difficult embedding argos as subdirectory of bigger project.
>
> I also provide:
>
>    - Fix for string_utilities.h (this produce compilation error for me on
>    g++ 5.2).
>    - Change to take ARGOS_PLUGIN_PATH variable paths above predefined
>    paths. This allows to always take currently build libraries and skip those
>    installed in system.
>
> Please review if it is useful for you.
>
> PS. You can check how I used it in my repository
> <https://github.com/pawel-jakubowski/coverage-search>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ilpincy/argos3/pull/18
> Commit Summary
>
>    - Allow argos to be build inside other cmake project
>    - Fix compilation errors
>    - Add cmake above src
>
> File Changes
>
>    - *A* CMakeLists.txt
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-0> (4)
>    - *M* src/CMakeLists.txt
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-1> (30)
>    - *M* src/cmake/ARGoSBuildFlags.cmake
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-2> (2)
>    - *M* src/cmake/ARGoSCreateDocs.cmake
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-3> (4)
>    - *M* src/cmake/ARGoSPackaging.cmake
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-4> (14)
>    - *M* src/core/CMakeLists.txt
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-5> (2)
>    - *M* src/core/utility/plugins/dynamic_loading.cpp
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-6> (2)
>    - *M* src/core/utility/string_utilities.h
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-7> (2)
>    - *M* src/plugins/simulator/physics_engines/dynamics2d/CMakeLists.txt
>    <https://github.com/ilpincy/argos3/pull/18/files#diff-8> (2)
>
> Patch Links:
>
>    - https://github.com/ilpincy/argos3/pull/18.patch
>    - https://github.com/ilpincy/argos3/pull/18.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ilpincy/argos3/pull/18>
>



-- 
Carlo Pinciroli, Ph.D.
http://carlo.pinciroli.net/

**Comment by pawel-jakubowski** [comment]
I assumed that I will try to play with code (maybe extend it somehow - I particularly look at adding ability to read configurations written as json file) and I want convenient environment to do so :)

I will understand if you consider this redundant or irrelevant to your framework.

**Comment by ilpincy** [comment]
On Wed, Apr 6, 2016 at 2:23 PM, Paweł Jakubowski <notifications@github.com>
wrote:

> I particularly look at adding ability to read configurations written as
> json file
>
That looks like an interesting addition. Keep me posted!

> I will understand if you consider this redundant or irrelevant to your
> framework.
>
The compilation fixes are very relevant, and I will surely keep them. As
soon as I have a little time, I'll go through the changes in the CMake
files. The changes you made look very well targeted, and I just want to
make sure there are no unwanted side effects.

Thanks again for your contribution!

Cheers,
Carlo

-- 
Carlo Pinciroli, Ph.D.
http://carlo.pinciroli.net/

**Comment by ilpincy** [comment]
Hi Pawel,

I kept your changes regarding
- compilation issues
- ARGOS_PLUGIN_PATH directory being checked before system directories
- FPS counter

Thanks a lot for your work, and feel free to propose more fixes in the future!

Cheers,
Carlo

**Comment by pawel-jakubowski** [comment]
I'm glad I could help :)

PS. My rather simple FPS counter wasn't a part of this pull request. Did it update automatically, or you choose it directly from fork repo?

**Comment by ilpincy** [comment]
It was added by Github in this merge request. I think it's a cool addition!

**Pull request closed without merging**
