### PR TITLE
LuA controller is now capable of reading parameters from the configurati...

### PR DESCRIPTION
**Pull request by hikhvar**
...on file and make them available to the lua script via the table robot.params.

The parameters are child tags of the params tag. The tag name is the key and the text between the tags becomes the values. The values are always passed as string to the lua controller. The type casting have to be done by the lua script. In the example below, the robot.params table has a key "test" with the value "Hello World". The keys can be arbitrary choosen.

<lua_controller id="red">
...
  <params script="lua_controller/red.lua">
    <test>Hello World</test>
  </params>
</lua_controller>

### CODE REVIEW

**Comment by hikhvar** [comment]
Have to rework this change! In this implementation the robot.params table is not available in the init() function of the LuA controller.

**Comment by ilpincy** [comment]
Thanks for the contribution! I think it's a great idea to have this done in ARGoS. I'll wait for a revised version.

I have two questions:

1. In the hello world example, why do you want 'test' to be a tag by itself? Why not an attribute?
2. How does one convert from string to number? You'd do it by hand in Lua?

**Comment by hikhvar** [comment]
Hello, you are welcome! I needed this feature any way, why not push it to upstream ;)

Regarding your questions: 
1. Actually I'm not that familiar with C++. The only Iterator found by me was the Iterator over the child tags of the params tag. To support arbitrary names for the passed parameters, I iterate over all child tags and use their names as parameter name. I could rework and iterate over all attributes if you think it is more like the ARGoS configuration file works.

2. As I want to make the parameter passing as generic as possible, I pass the parameters as strings, since LuA has an function to convert numbers from string to "number" the internal LuA type for numbers. [1] This allows the user to pass strings, integers and floating points as parameters. This solution assumes that the user knows the parameters of his controller and also the corresponding type.

[1] http://www.lua.org/manual/5.2/manual.html#pdf-tonumber

**Comment by ilpincy** [comment]
1. I'd probably prefer iterating over attributes because it suits more the kind of operation your are doing: you want to have a list of key-values in robot.params. Using tags allows people to have nested content, which you don't support (and it's fine!). I think it's more intuitive with attributes.

2. It's a totally acceptable solution. Go for it! :-)

Thanks again!

**Comment by hikhvar** [comment]
Hello, 

did you have a look at the pull request? I moved the parameters to the tags.

**Comment by ilpincy** [comment]
Sorry, I got carried away with work. Thanks a lot for your contribution! :-)
I will push it, along with other improvements I'm making to ARGoS. It will definitely be in the next release.
Thanks again! :-)

**Pull request closed without merging**
